---
all:
  children:
    routers:
      hosts:
        csr1.eveng.com:
        csr2.eveng.com:
    management:
      hosts:
        csr-mgmt.eveng.com:
  vars:
    ansible_network_os: "ios"
    ansible_user: "ansible"
    ansible_password: "ansible"
    ansible_python_interpreter: "/usr/bin/env python"
    ntp_server1: "192.0.2.1"

