---
- name: "Manage DHCP in the mgmt router"
  hosts: "management"
  connection: network_cli
  gather_facts: false
  tasks:
     - name: "TASK 1: Apply the dhcp configuration for CSR"
       ios_config:
         parents: "ip dhcp pool CSR1"
         lines:
           - network 10.8.11.0 255.255.255.0
           - default-router 10.8.11.1
           - domain-name eveng.com
           - dns-server 8.8.8.8
           - lease 0 8
       register: "dhcp_updates"
    
     - name: "TASK 4: Print changes if they happen"
       debug:
         var: "dhcp_updates.updates"
       when: "dhcp_updates.updates is defined"

     - name: save running to startup when modified
       ios_config:
         save_when: modified

