---
- name: "Manage DHCP in the mgmt router"
  hosts: "csr-mgmt.eveng.com"
  connection: network_cli
  gather_facts: false
  tasks:
     - name: "TASK 1: Apply the dhcp configuration for CSR"
       ios_config:
         parents: "ip dhcp pool CSR1"
         lines:
           - "host {{ item.ip }}"
           - "client-identifier {{ item.mac }}"
           - default-router 10.8.11.1
           - domain-name cisco.com
           - dns-server 8.8.8.8
         with_items: "{{ reservations }}"
     

     - name: save running to startup when modified
       ios_config:
         save_when: modified

