---
# Usage example: ansible-playbook practicejinja.yml --extra-vars template="1-ipaddr"
# - name: "Generate spine configuration"
#   hosts: "Spines"
#   tasks:
#   - template: src="template_spine.j2" dest=result_spine.txt

- name: "Load and commit configuration"
  hosts: "Spines"
  vars:
#    ansible_python_interpreter: "/usr/bin/env python"
  tasks:
    - name: "Load a configuration from a Jinja2 template and commit"
      juniper.device.config:
        load: "merge"
        template: "template_spine.j2"
        format: "text"
  


