---
- name: "Load and commit configuration"
  hosts: all
  connection: netconf
  gather_facts: no
  tasks:
  - name: "Generates config for Cleaning up interfaces"
    template:
      src: "spine_delete_ifaces.j2"
      dest: "{{inventory_hostname}}_delete_ifaces.txt"
  
  - name: "Generates config for Adding IPs to interfaces"
    template:
      src: "spine_create_ifaces.j2"
      dest: "{{inventory_hostname}}_create_ifaces.txt"

  - name: "Cleaning up interfaces" 
    junipernetworks.junos.junos_config:
      src: "{{inventory_hostname}}_delete_ifaces.txt"
      #update: "override"

  - name: "Adding IPs to interfaces"
    junipernetworks.junos.junos_config:
      src: "{{inventory_hostname}}_create_ifaces.txt"
      #update: "override"

