---
all:
  children:
    Spines:
      hosts:
        Spine-1.eveng.com:
        Spine-2.eveng.com:
    Leafs:
      hosts:
        Leaf-1.eveng.com:
        Leaf-2.eveng.com:
        Leaf-3.eveng.com:
        Leaf-4.eveng.com:
  vars:
    ansible_network_os: "junipernetworks.junos.junos"
    ansible_python_interpreter: "/usr/bin/env python3.6"

