---
- name: "Test ansuble connecttion"
  hosts: "management"
  connection: network_cli
  gather_facts: false
  tasks:
     - name: show_command
       ios_command:
          commands:
             - show ip interface brief
       register: output_command
       become_method: enable
       become: yes
     - name: show_variable
       debug:
         var: output_command


