---
all:
  children:
    routers:
      hosts:
        csr1.eveng.com.eveng.com:
        csr2.eveng.com.eveng.com:
        csr3.eveng.com.eveng.com:
        csr4.eveng.com.eveng.com:
        csr5.eveng.com.eveng.com:
        csr6.eveng.com.eveng.com:
        csr7.eveng.com.eveng.com:
        csr8.eveng.com.eveng.com:
...
